### ISSUE TITLE
HTTP Header Inside a Conditional

### ISSUE THREAD

**Issue by kgrote** [rsanchez/http_header#16]
I have HTTP Header inside a conditional, but it always redirects the page regardless of whether the condition is true or not:

````
{if some_conditional}
    {exp:http_header
        status='301'
        location='{some_location}'
        terminate='yes'
    }
{if:else}
    <p>Hello world.</p>
{/if}
````

**Comment by rsanchez** [comment]
Which version of EE? If you're on 2.8 or older, then your problem is that advanced conditionals are parsed late. If you're on 2.9, I honestly don't know with all the conditional Changes they've made since then.

**Comment by kgrote** [comment]
I'm on 2.9+

**Comment by rsanchez** [comment]
I'd say report it as a bug to EllisLab. There's nothing I can do from within a plugin to control execution in a conditional.

**Comment by kgrote** [comment]
Will do, thanks!
