### ISSUE TITLE
content_disposition downloads in safari

### ISSUE THREAD

**Issue by paulcripps** [rsanchez/http_header#18]
We're using http_header 1.0.8 in EE v2.8.1 - Build Date: 20140314 

This code works:

    {exp:http_header content_disposition="attachment" filename="myfile.csv"}

But in Safari Version 8.0.5 (10600.5.17) the downloaded file name changes to myfile.csv.html

Any thoughts on a fix?

**Comment by rsanchez** [comment]
Try adding a Content-Type:

```
{exp:http_header content_type="application/octet-stream" content_disposition="attachment" filename="myfile.csv"}
```

Not sure if it'll work, but worth a shot.
