### ISSUE TITLE
Devot:ee version 1.0.7

### ISSUE THREAD

**Issue by leevigraham** [rsanchez/http_header#19]
Any chance you can update the version on devot:ee so lamplighter doesn't display a warning?

![screen shot 2015-07-10 at 10 47 49 am](https://cloud.githubusercontent.com/assets/25124/8610101/284aee0e-26f1-11e5-886f-d94ebfe8e685.png)

**Comment by rsanchez** [comment]
Done! And pushed a new version 1.0.9.

**Comment by leevigraham** [comment]
:+1:
